language: python
python:
  - "2.7"
addons:
  - postgresql: "9.3"
install:
  - pip install -r requirements.txt
env:
  - PRISM_DEBUG=1
script:  python -m unittest discover ./test
# notifications:
#   email: false
